services:
  minerl:
    build:
      context: .
      dockerfile: Dockerfile
    image: minerl-dev:latest
    working_dir: /workspace
    environment:
      DISPLAY: 172.26.160.1:0
      TMPDIR: /opt/tmp
      TEMP: /opt/tmp
      TMP: /opt/tmp
      JAVA_HOME: /opt/conda
    volumes:
      - .:/workspace
      - minerl-tmp:/opt/tmp
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
    network_mode: host
    shm_size: "4gb"
    stdin_open: true
    tty: true
    command: tail -f /dev/null

volumes:
  minerl-tmp: